### PR TITLE
Fixes and misc

### PR DESCRIPTION
**Pull request by emmedici**
I've added the `cargo workspace` feature & I launched `clippy` with `--fix` on the whole codebase.

### CODE REVIEW

**Comment by JasterV** [comment]
@emmedici I've made some updates on the codebase, could you pull and do that again? :D

**Comment by JasterV** [comment]
Also I would prefer to keep the projects isolated without bringing in any workspace, I think you can run clippy independently in each project

**Comment by emmedici** [comment]
ok no worries @JasterV, I thought that the workspace missing was an oversight, not a choice. I will rebase it no problem :)

**Comment by emmedici** [comment]
ok, dropped the workspace & made re-run clippy on the codebase.

**Review by JasterV — APPROVED** [review]
Looks good :D

**Pull request merged**
